name: "Build wheels"
on:
  push:
    branches:
      - dev/master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v4
      - name: setup python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install poetry build
  
      - name: Install dependencies
        run: |
          poetry install
      
      - name: Build artifacts
        run: |
          python -m build
      
      - name: Upload all artifacts
        uses: actions/upload-artifact@v4.5.0
        with:
          name: dist
          path: dist/*
